# Generated by Django 2.2.9 on 2021-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamneto',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Nome'),
        ),
    ]
