# Generated by Django 2.2.9 on 2021-04-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210410_0216'),
        ('departamentos', '0002_auto_20210410_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamneto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
    ]
