# Generated by Django 2.2.9 on 2021-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20210410_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='funcionario',
            new_name='pertence',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='', upload_to='documentos'),
            preserve_default=False,
        ),
    ]
