# Generated by Django 2.2.9 on 2021-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20210415_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='pertence',
            new_name='funcionrio',
        ),
    ]
