# Generated by Django 2.2.9 on 2021-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'RegistroHoraExtra',
                'verbose_name_plural': 'RegistroHoraExtras',
            },
        ),
    ]
